CREATE SEQUENCE IF NOT EXISTS CUSTOMER_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS CUSTOMER
(
    id     BIGINT       NOT NULL,
    name   VARCHAR(255) NOT NULL,
    email  VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);